name: haffez
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-248.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^0.23.0+1

  flutter_rating_bar: ^4.0.0

  flutter_screenutil: ^5.0.0+2

  date_format: ^2.0.5
  timeago: ^3.2.2

  get: ^4.3.8
  get_storage: ^2.0.3

  firebase_core: "^1.10.0"
  firebase_auth: "^3.2.0"
  cloud_firestore: "^3.1.0"

  rflutter_alert: ^2.0.4

  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-black.ttf
        - asset: assets/fonts/cairo-bold.ttf
        - asset: assets/fonts/cairo-extra-bold.ttf
        - asset: assets/fonts/cairo-extra-light.ttf
        - asset: assets/fonts/cairo-light.ttf
        - asset: assets/fonts/cairo-medium.ttf
        - asset: assets/fonts/cairo-regular.ttf
        - asset: assets/fonts/cairo-semi-bold.ttf